package com.peekaboo.design_system

// Common
const val BaeBae = "BaeBae"
const val CourseNumberFormat = "%d/%d"
const val Next = "next"
const val Add = "추가"
const val Finish = "finish"
const val Question = "?"
const val And = " and "
const val BackToMain =  "Back to Main"
const val Percent = "%d%%"
const val CancelDiagnosis = "Cancel"
const val CreateDiagnosis = "Create"

// Word
const val Korea = "한국"
const val Korean = "한국어"
const val America = "America"
const val English = "English"
const val Male = "남자"
const val FeMale = "여자"
const val BloodTypeA = "A형"
const val BloodTypeAB = "AB형"
const val BloodTypeB = "B형"
const val BloodTypeO = "O형"

// OnBoarding
const val OnBoardingTitle = "BaeBae 등록"
const val LanguageChoiceTitle = "앱을 사용할 지역과 언어를 선택해 주세요."
const val LocationChoiceSemiTitle = "현재 거주하는 지역을 선택해 주세요."
const val LanguageChoiceSemiTitle = "현재 사용하는 언어를 선택해 주세요."
const val PersonalInputTitle = "증상 진단을 사용하는 대상의 기본 정보를\n입력해 주세요."
const val BirthInputSemiTitle = "출생일을 작성해 주세요."
const val BirthInputHint = "0000-00-00의 형태로 작성해 주세요."
const val SexChoiceSemiTitle = "성별을 선택해 주세요."
const val BloodTypeSemiTitle = "혈액형을 선택해 주세요."
const val SkinColorSelectTitle = "증상 진단을 사용하는 대상의 skin color를\n선택해 주세요."
const val SkinColorSelectSemiTitle = "대상과 가장 비슷한 색상을 선택해 주세요."
const val AllergyInputTitle = "증상 진단을 사용하는 대상의 알러지 유무를\n작성해 주세요."
const val AllergyInputSemiTitle = "원하는 만큼 추가해서 작성해 주세요. 없다면 작성하지 않아도 괜찮습니다."
const val AllergyInputHint = "예) 꽃가루 알레르기, 식품 알레르기 등"
const val CautionNotice = "증상 진단 용도 외에는 사용되거나 유출되지 않습니다."
const val DiseaseHistoryInputTitle = "증상 진단을 사용하는 대상의 질병 발병 이력을\n작성해 주세요."
const val DiseaseHistoryInputSemiTitle = "원하는 만큼 추가해서 작성해 주세요. 없다면 작성하지 않아도 괜찮습니다."
const val DiseaseHistoryInputHint = "예) 홍역, 수두 등"

// Home
const val HomeSemiTitle = "Simply input, Smart diagnosis\nStay with "
const val HomeDiagnosingBoxTitle = "Does your child have\nan unknown "
const val SkinCondition = "skin condition"
const val HomeDiagnosingBoxSemiTitle = "Try AI diagnosing right now!"
const val DiagnosingBtn = "Diagnosing"
const val DiagnosisHistorySemiTitle = "Check my record"
const val DiagnosingTypeListTitle = "Types of Skin Diseases"
const val DiagnosingTypeFullView = "Full View"
const val DiagnosingTypeListSemiTitle = "Check the symptoms quickly\nbefore diagnosing the symptoms!"

// Diagnosis
const val DiagnosisTitle = "Diagnosis of Symptoms"
const val DiagnosisSelectArea = "Pleas select the area\nwhere you have symptoms"
const val DiagnosisSelectPicture = "Please take a picture\nof the Symptom and register it"
const val DiagnosisExplainTitle = "Please explain the symptoms"
const val DiagnosisExplainHint = "Please write down the symptoms in detail.\nThe more detailed you write,\nthe more accurate the results will be."
const val DiagnosisSelectAreaFront = "FRONT"
const val DiagnosisSelectAreaSide = "SIDE"
const val DiagnosisSelectAreaBack = "BACK"
const val DiagnosisResultTitle = "Result of Diagnosis"
const val DiagnosisResultRanking = "[Disease Diagnosis Result]\n\nThe results suggest\n"
const val DiagnosingResultRankingEnd = " is the most probable condition."
const val DiagnosingCustomizedResult = "Customized Information"
const val DiagnosingResultEachTitle = "Symptom Description"
const val DiagnosingResultBtn = "Download Medical Chart"
const val DiagnosingChooseLanguage = "Choose a language"

// Diagnosis History
const val DiagnosisHistoryTitle = "Diagnosis History"
const val DiagnosisEmptyTitle = "No symptom diagnosis results yet"
const val MajorSymptoms = "Major symptoms: "
const val ImproveMethod = "How to improve: "
const val CustomizedInfo = "Customized Information: "
const val DiagnosisHistoryRanking = "In addition, other results with a high probability of diagnosis were "
const val DiagnosisRating = "%s"

// Diagnosis Quick
const val QuickDiagnosisTitle =  "Quick Diagnosis"
const val QuickDiagnosisSemiTitle = "Types of Skin Disease"
const val QuickDiseaseSymptomsTitle = "Major Symptoms"
const val QuickDiseaseSymptomsRating = "Risk Rating Level"
const val QuickDiseaseSymptomsCategory = "Category"
const val QuickDiseaseSymptomsType = "Type"
const val QuickDiseaseSymptomsSite = "Site"
const val QuickDiseaseSymptomsReason = "Reason"
const val QuickDiseaseFirstAid = "First Aid(A Child Standard)"
const val QuickDiseaseFirstAidMild = "Mild"
const val QuickDiseaseFirstAidSevere = "Severe"
const val QuickDiseaseMedicine = "Prescription Medicine"
const val QuickDiseasePreventiveMeasure = "Preventive Measure"
const val QuickDiseasePrecautions = "Precautions"
const val QuickDiseaseAdditionalBtn = "Additional Diagnosis"