package com.peekaboo.design_system

// Common
const val BaeBae = "BaeBae"
const val CourseNumberFormat = "%d/%d"
const val Next = "next"
const val Add = "추가"
const val Finish = "finish"
const val Question = "?"
const val And = " and "
const val BackToMain =  "Back to Main"
const val Percent = "%d%%"
const val CancelDiagnosis = "Cancel"
const val CreateDiagnosis = "Create"
const val Empty = ""

// Word
const val Korea = "한국"
const val Korean = "한국어"
const val America = "America"
const val English = "English"
const val Male = "남자"
const val FeMale = "여자"
const val BloodTypeA = "A형"
const val BloodTypeAB = "AB형"
const val BloodTypeB = "B형"
const val BloodTypeO = "O형"

// OnBoarding
const val OnBoardingTitle = "BaeBae Registration"
const val LanguageChoiceTitle = "Please select your region and language."
const val LocationChoiceSemiTitle = "Please select your current region."
const val LanguageChoiceSemiTitle = "Please select your preferred language."
const val PersonalInputTitle = "Please enter basic information\nfor the person receiving symptom analysis."
const val BirthInputSemiTitle = "Please enter the date of birth"
const val BirthInputHint = "Please use the format: YYYY-MM-DD."
const val SexChoiceSemiTitle = "Please select the gender."
const val BloodTypeSemiTitle = "Please select the blood type."
const val SkinColorSelectTitle = "Please select the skin color\nof the person being assessed."
const val SkinColorSelectSemiTitle = "Choose the shade\nthat most closely matches their skin tone."
const val AllergyInputTitle = "Please enter any allergies the person may have."
const val AllergyInputSemiTitle = "You can add as many as you'd like, or leave this blank if none."
const val AllergyInputHint = "ex) pollen allergy, food allergy"
const val CautionNotice = "This information will be used only for symptom analysis and will not be shared."
const val DiseaseHistoryInputTitle = "Please enter any previous\nmedical conditions the person has had."
const val DiseaseHistoryInputSemiTitle = "You may list as many as needed, or leave it blank if there are none."
const val DiseaseHistoryInputHint = "ex) measles, chickenpox"

// Home
const val HomeSemiTitle = "Simply input, Smart diagnosis\nStay with "
const val HomeDiagnosingBoxTitle = "Does your child have\nan unknown "
const val SkinCondition = "skin condition"
const val HomeDiagnosingBoxSemiTitle = "Try AI diagnosing right now!"
const val DiagnosingBtn = "Diagnosing"
const val DiagnosisHistorySemiTitle = "Check my record"
const val DiagnosingTypeListTitle = "Types of Skin Diseases"
const val DiagnosingTypeFullView = "Full View"
const val DiagnosingTypeListSemiTitle = "Check the symptoms quickly\nbefore diagnosing the symptoms!"

// Diagnosis
const val DiagnosisTitle = "Diagnosis of Symptoms"
const val DiagnosisSelectArea = "Pleas select the area\nwhere you have symptoms"
const val DiagnosisSelectPicture = "Please take a picture\nof the Symptom and register it"
const val DiagnosisExplainTitle = "Please explain the symptoms"
const val DiagnosisExplainHint = "Please write down the symptoms in detail.\nThe more detailed you write,\nthe more accurate the results will be."
const val DiagnosisSelectAreaFront = "FRONT"
const val DiagnosisSelectAreaSide = "SIDE"
const val DiagnosisSelectAreaBack = "BACK"
const val DiagnosisResultTitle = "Result of Diagnosis"
const val DiagnosisResultRanking = "[Disease Diagnosis Result]\n\nThe results suggest\n"
const val DiagnosingResultRankingEnd = " is the most probable condition."
const val DiagnosingCustomizedResult = "Customized Information"
const val DiagnosingResultEachTitle = "Symptom Description"
const val DiagnosingResultBtn = "Download Medical Chart"
const val DiagnosingChooseLanguage = "Choose a language"

// Diagnosis History
const val DiagnosisHistoryTitle = "Diagnosis History"
const val DiagnosisEmptyTitle = "No symptom diagnosis results yet"
const val MajorSymptoms = "Major symptoms: "
const val ImproveMethod = "How to improve: "
const val CustomizedInfo = "Customized Information: "
const val DiagnosisHistoryRanking = "In addition, other results with a high probability of diagnosis were "
const val DiagnosisRating = "%s"

// Diagnosis Quick
const val QuickDiagnosisTitle =  "Quick Diagnosis"
const val QuickDiagnosisSemiTitle = "Types of Skin Disease"
const val QuickDiseaseSymptomsTitle = "Major Symptoms"
const val QuickDiseaseSymptomsRating = "Risk Rating Level"
const val QuickDiseaseSymptomsCategory = "Category"
const val QuickDiseaseSymptomsType = "Type"
const val QuickDiseaseSymptomsSite = "Site"
const val QuickDiseaseSymptomsReason = "Reason"
const val QuickDiseaseFirstAid = "First Aid(A Child Standard)"
const val QuickDiseaseFirstAidMild = "Mild"
const val QuickDiseaseFirstAidSevere = "Severe"
const val QuickDiseaseMedicine = "Prescription Medicine"
const val QuickDiseasePreventiveMeasure = "Preventive Measure"
const val QuickDiseasePrecautions = "Precautions"
const val QuickDiseaseAdditionalBtn = "Additional Diagnosis"